name: Deployment exercise 1
on: push
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
        - name:  Get the Code from repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm ci
        - name : Lint
          run: npm run lint
        - name: Run tests
          run: npm test
        - name: Build Project
          run: npm run build
        - name: Deploy
          run: echo "Deploying the product...."